sudo: false
dist: trusty
language: php


php:
  - 5.6
  - 7
  - 7.1



before_script:
  # install deps and UF
  - composer install
  - php bakery migrate

script:
  # run unit tests
  - composer test
